### PR TITLE
Adding XMODEM receive capability

### PR DESCRIPTION
**Pull request by phooky**
I've added XMODEM receive capability to the library, along with tests using "sb" and loopback tests against the sending portion.

### CODE REVIEW

**Comment by awelkie** [comment]
Looks great, thanks for the PR! It looks like this only handles block sizes of 128 and not 1024, whereas the send method does both 128 and 1024. Would you be willing to add support for both block sizes? If not that's fine and this is still good to merge in, but maybe add something in the docstring mentioning the limitation.

**Comment by phooky** [comment]
Ah, good point. I should have time to get back to this code later in the week; I'll see what I can do!

**Comment by phooky** [comment]
Okay, that should do it. Give it a whirl!

**Comment by awelkie** [comment]
Looks great. Thanks!

**Pull request merged**
